Server: # 服务配置
  RunMode: debug # release 为生产模式
  Address: :8080 # 监听端口
  ReadTimeout: 5s
  WriteTimeout: 5s
  DefaultContextTimeout: 10s #默认超时时间
App: # App配置文件
  Name: chat  # App名称
  Version: 1.0.0 # 版本号
  StartTime: "2002-07-11" # 启动时间
  MachineID: 0 # 机器ID
Log: # 日志配置文件
  Level: debug
  LogSavePath: "storage/applogs/" # 日志保存路径
  HighLevelFile: error          # 高级别日志文件名
  LowLevelFile: info          # 低级别文件名
  LogFileExt: .log          # 日志文件后缀
  MaxSize: 10 # 日志文件最大大小 MB
  MaxAge: 30 # 日志文件最大保存天数
  MaxBackups: 7 # 最大备份数
  Compress: false # 是否压缩
Page: # 分页
  DefaultPageSize: 10
  MaxPageSize: 200
  PageKey: page
  PageSizeKey: page_size
Rule: # 规则配置
  UsernameLenMax: 32 # 用户名最大长度
  UsernameLenMin: 1 # 用户名最小长度
  PasswordLenMax: 32 # 密码最大长度
  PasswordLenMin: 6 # 密码最小长度
  CodeLength: 6 # 验证码长度
  UserMarkDuration: 60s # 用户发送验证码间隔时间
  CodeMarkDuration: 1h # 验证码有效时间
  AccountNumMax: 5 # 用户账号最大数量
  DefaultAvatarURL: "https://avatars.githubusercontent.com/u/76676061?v=4" # 默认头像
  BiggestFileSize: 1024000
Auto: # 自动任务配置
  Retry:
    Duration: 5s # 重试间隔时间
    MaxTimes: 3 # 最大重试次数
  DeleteExpiredFileDuration: 12h
Worker: # 工作池配置
  TaskChanCapacity: 50 # 任务队列容量
  WorkerChanCapacity: 50 # 工作队列容量
  WorkerNum: 10 # 工作池数量
Limit: # 限流
  IPLimit: # IP限流
    Cap: 10           # 令牌桶容量
    GenNum: 5         # 令牌产生数
    GenTime: 1       # 令牌产生时间
    Cost: 1           # 本次取走的令牌数
  APILimit: # API限流
    Email:
      - Count: 5
        Duration: 1s
        Burst: 5
      - Count: 30
        Duration: 1m
        Burst: 5
    Upload:
      - Count: 1
        Duration: 1s
        Burst: 1
